name: GitHub-Profile-3D-Contrib

on:
  schedule: # 23:59 KST == 14:59 UTC
    - cron: "59 14 * * 1-5"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      
      - name: Check for Today's Commit
        id: check_commit
        run: |
          echo "Checking commits for user: ${{ github.repository_owner }}"
          commits=$(curl -s -H "Authorization: token ${{ secrets.TOKEN }}" "https://api.github.com/search/commits?q=author:${{ github.repository_owner }}+committer-date:$(date +%Y-%m-%d)" -H "Accept: application/vnd.github.cloak-preview")
          if [[ $(echo "$commits" | jq '.total_count') -gt 0 ]]; then
            echo "commit_exists=true" >> $GITHUB_ENV
          else
            echo "commit_exists=false" >> $GITHUB_ENV
          fi

      - name: Generate GitHub Profile 3D Contrib
        if: env.commit_exists == 'true'
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push
        if: env.commit_exists == 'true'
        run: |
          git config user.name ${{USERNAME}}
          git config user.email ${{USEREMAIL}}
          git add -A .
          git commit -m "generated"
          git push
